[minor_change] try login for pwd set
CiscoDevNet/terraform-provider-aci pull request #1001
Opened 2023-01-23 16:27 UTC by akinross

fixes #984

2023-01-24 07:10 UTC, akinross commented on aci/resource_aci_aaauser.go
> +	if loginSuccess || d.HasChange("pwd") {
tested without and is redundant, so removed the hasChange

2023-01-24 07:11 UTC, akinross commented on aci/resource_aci_aaauser.go
> +		d.Set("pwd", d.Get("pwd").(string))
correct, the additional check provided same result but redundant so removed

2023-01-24 13:19 UTC, lhercot commented on aci/resource_aci_aaauser.go
> +		d.Set("pwd", d.Get("pwd").(string))
Still there. Check apply, manual change in APIC and re-apply.

2023-01-31 13:05 UTC, lhercot requested changes

2023-01-31 13:05 UTC, lhercot commented on aci/resource_aci_aaauser.go
> +		log.Printf("[DEBUG] Authentication failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
Do we want to log the password?

2023-01-31 13:05 UTC, lhercot commented on aci/resource_aci_aaauser.go
> +		log.Printf("[DEBUG] Creation of authentication request failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
Do we want to log the password?

2023-01-31 13:05 UTC, lhercot commented on aci/resource_aci_aaauser.go
> +	log.Printf("[DEBUG] Authentication succceeded for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
Do we want to log the password?

2023-01-31 13:36 UTC, akinross commented on aci/resource_aci_aaauser.go
> +		log.Printf("[DEBUG] Creation of authentication request failed for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
no will remove

2023-01-31 13:36 UTC, akinross commented on aci/resource_aci_aaauser.go
> +	log.Printf("[DEBUG] Authentication succceeded for local user: '%s:%s'.", d.Get("name").(string), d.Get("pwd").(string))
no will remove

2023-01-31 13:41 UTC, akinross commented on aci/resource_aci_aaauser.go
> +
can't access the skipLoggingPayload of client since it is private to the package, would need to change in aci-go-client?

2023-01-31 20:12 UTC, anvitha-jain submitted a review, later dismissed
LGTM

2023-02-03 13:58 UTC, lhercot requested changes

2023-02-03 13:58 UTC, lhercot commented on aci/resource_aci_aaauser.go
> +			log.Printf("[DEBUG] SETTING SKIP")
Do we need this log?

2023-02-03 14:00 UTC, akinross commented on aci/resource_aci_aaauser.go
> +			log.Printf("[DEBUG] SETTING SKIP")
no thought i removed all logs

2023-02-03 14:04 UTC, merged