Added the address_type_controls to BGP Route Summarization resource
CiscoDevNet/terraform-provider-aci pull request #1040
Opened 2023-04-24 15:01 UTC by sajagana

Note:

Added `summary-only` to the `ctrl` attribute.
Also added the `address_type_controls` to BGP Route Summarization resource

2023-04-24 16:28 UTC, akinross commented on website/docs/r/bgp_route_summarization.html.markdown
> +- `address_type_controls` - (Optional) Address Type Controls of the BGP Route Summarization object. Allowed values are "af-ucast", "af-mcast", "af-label-ucast". Default is "af-ucast". Type: List.
Is this default correct?

2023-04-25 08:35 UTC, akinross submitted a review, later dismissed
LGTM

2023-04-26 18:25 UTC, shrsr requested changes

2023-04-26 18:25 UTC, shrsr commented on website/docs/r/bgp_route_summarization.html.markdown
> +  ctrl                  = sort(["summary-only", "as-set"])                 # Use the sorted list to handle identical changes
Remove comments # Use the sorted list to handle identical changes and # Use the sorted list to handle identical changes

2023-04-26 18:25 UTC, shrsr commented on examples/bgp_route_summarization/main.tf
> +  ctrl                  = sort(["summary-only", "as-set"])                 # Use the sorted list to handle identical changes
What does this mean ->Use the sorted list to handle identical changes?

Isn't TF able to differentiate between  ["summary-only", "as-set"]  and ["as-set", "summary-only"]?

2023-05-05 13:09 UTC, shrsr requested changes

2023-05-09 06:43 UTC, akinross submitted a review, later dismissed
LGTM

2023-05-09 06:51 UTC, sajagana commented on aci/utils.go
> +func suppressTypeListDiffFunc(key, oldValue, newValue string, d *schema.ResourceData) bool {
Created an issue to track other resource changes: https://github.com/CiscoDevNet/terraform-provider-aci/issues/1044

2023-05-09 12:45 UTC, shrsr submitted a review, later dismissed
LGTM (Discussed the comments with Sabari )

2023-05-09 18:07 UTC, anvitha-jain submitted a review, later dismissed
LGTM

2023-05-10 09:21 UTC, lhercot requested changes

2023-05-11 07:09 UTC, sajagana commented on aci/resource_aci_bgprtsummpol.go
> +					"summary-only",
The ctrl attribute allows to set empty(none) string, but none is not in the list of valid values.

2023-05-15 13:26 UTC, shrsr approved these changes
LGTM

2023-05-16 19:28 UTC, lhercot approved these changes
LGTM

2023-05-16 19:31 UTC, merged