Fix for the list element order mismatch issue on the TypeList attributes
CiscoDevNet/terraform-provider-aci pull request #1051
Opened 2023-05-25 08:22 UTC by sajagana

Note:

Fix for the list element order mismatch issue on the TypeList attributes also updated a few examples.

2023-05-25 15:14 UTC, akinross requested changes

2023-05-25 15:14 UTC, akinross commented on examples/ospf_timers/main.tf
>    tenant_dn           = aci_tenant.tenentcheck.id
```suggestion
  tenant_dn           = aci_tenant.footenant.id
```

2023-05-26 10:45 UTC, akinross approved these changes
LGTM

2023-05-26 14:20 UTC, shrsr requested changes

2023-05-26 14:20 UTC, shrsr commented on website/docs/r/cloud_subnet.html.markdown
> +* `scope` - (Optional) List of domain applicable to the capability. Allowed values are "public", "private" and "shared". Default is ["private"].
List of domains applicable to the capability.

2023-05-26 14:44 UTC, shrsr approved these changes
LGTM

2023-05-30 18:08 UTC, anvitha-jain approved these changes
LGTM

2023-06-16 19:44 UTC, merged