[bugfix] Changed relationship attribute to gather target dn instead  of name
CiscoDevNet/terraform-provider-aci pull request #1053
Opened 2023-05-30 21:04 UTC by shrsr

2023-05-31 06:50 UTC, sajagana requested changes

2023-05-31 06:50 UTC, sajagana commented on aci/resource_aci_infraportblk.go
Import is not working for the "relation_infra_rs_acc_bndl_subgrp" attribute.
Also, the data source attributes are not matching with resource attributes.

2023-05-31 06:50 UTC, sajagana commented on website/docs/d/access_port_block.html.markdown
relation_infra_rs_acc_bndl_subgrp is missing.

2023-05-31 13:33 UTC, shrsr commented on aci/resource_aci_infraportblk.go
ok

2023-05-31 13:33 UTC, shrsr commented on website/docs/d/access_port_block.html.markdown
ok

2023-06-01 06:15 UTC, akinross approved these changes
LGTM

2023-06-06 13:42 UTC, sajagana approved these changes
LGTM!

2023-06-20 15:52 UTC, anvitha-jain approved these changes
LGTM

2023-06-23 00:09 UTC, lhercot approved these changes
LGTM

2023-06-23 00:10 UTC, merged