[ignore] documentation updates to mention cloud network controller in…
CiscoDevNet/terraform-provider-aci pull request #1059
Opened 2023-06-20 10:27 UTC by akinross

…stead of aci cloud, cloud apic or cloud aci

fixes #1034

2023-06-21 20:46 UTC, anvitha-jain approved these changes
LGTM

2023-06-23 07:44 UTC, lhercot requested changes
Please apply same to rest of changes. If the string was ACI Cloud -> Cloud Network Controller Cloud.

2023-06-23 14:36 UTC, shrsr requested changes

2023-06-23 14:36 UTC, shrsr commented on website/docs/d/cloud_account.html.markdown
> +  Data source for Cloud Network Controller Cloud Account
Cloud Network Controller Cloud Account sounds confusing
Just a suggestion ->
Data source for the Cloud Account

2023-06-27 15:15 UTC, anvitha-jain approved these changes
LGTM

2023-06-28 07:16 UTC, sajagana approved these changes
LGTM!

2023-06-29 17:20 UTC, shrsr approved these changes
LGTM

2023-07-01 08:52 UTC, lhercot approved these changes
LGTM

2023-07-01 08:52 UTC, merged