Added a default to encap to ensure TF's idempotent behaviour in the resource 'l3out_floating_svi'
CiscoDevNet/terraform-provider-aci pull request #1114
Opened 2023-10-11 16:34 UTC by shrsr

2023-10-11 16:56 UTC, anvitha-jain submitted a review, later dismissed

2023-10-12 17:50 UTC, gmicol approved these changes

2023-10-16 14:06 UTC, sajagana requested changes
Add the missing attributes to the data source.

2023-10-16 14:06 UTC, sajagana commented on aci/resource_aci_l3extvirtuallifp.go
> +func compareConfigs(old []interface{}, new []interface{}) []interface{} {
```suggestion
func compareL3ExtRsDynPathAtt(old []interface{}, new []interface{}) []interface{} {
```

2023-10-16 14:06 UTC, sajagana commented on aci/resource_aci_l3extvirtuallifp.go
> +			updatedConfig := compareConfigs(configOld.(*schema.Set).List(), configNew.(*schema.Set).List())
```suggestion
			updatedConfig := compareL3ExtRsDynPathAtt(configOld.(*schema.Set).List(), configNew.(*schema.Set).List())
```

2023-10-16 16:26 UTC, shrsr commented on aci/resource_aci_l3extvirtuallifp.go
> +			updatedConfig := compareConfigs(configOld.(*schema.Set).List(), configNew.(*schema.Set).List())
ok

2023-10-16 16:26 UTC, shrsr commented on aci/resource_aci_l3extvirtuallifp.go
> +func compareConfigs(old []interface{}, new []interface{}) []interface{} {
ok

2023-10-18 17:42 UTC, akinross requested changes

2023-10-18 17:42 UTC, akinross commented on aci/resource_aci_l3extvirtuallifp.go
> +				}
Do we need this loop? Can't we get the encap value from old_map, and new_map directly?
```suggestion
				if old_map.(map[string]interface{})["encap"] == "unknown" && new_map.(map[string]interface{})["encap"] == "" {
					new_map.(map[string]interface{})["encap"] = "unknown"
					break
				}
```

2023-10-19 07:33 UTC, akinross approved these changes
LGTM

2023-10-19 17:55 UTC, gmicol approved these changes
LGTM

2023-10-20 12:29 UTC, sajagana approved these changes
LGTM!

2023-10-23 17:07 UTC, merged