Dataplane Learning for fvSubnet
CiscoDevNet/terraform-provider-aci pull request #1138
Opened 2023-12-10 19:10 UTC by mfr-6

Hello Team,

This PR aims to add data plane learning argument to fvSubnet.

Please carry out the review, thank you.

2023-12-13 10:32 UTC, akinross requested changes

2023-12-13 10:32 UTC, akinross commented on aci/data_source_aci_fvsubnet.go
> -				Optional: true,
I see you have changed to computed for attributes in data source and in the documentation. Is there a reason to skip next_hop_addr, msnlb + nested attributes, and anycast_mac? These can also all be changed to computed from what I see.

2023-12-13 10:32 UTC, akinross commented on website/docs/d/subnet.html.markdown
> +- `annotation` - (Read-Only) Annotation for object subnet.
Could you add ` Type: String.` consistently behind all string inputs?

2023-12-13 10:32 UTC, akinross commented on website/docs/d/subnet.html.markdown
> +- `relation_fv_rs_bd_subnet_to_out` - (Read-Only) Relation to class l3extOut. Cardinality - N_TO_M. Type - Set of String.
```suggestion
- `relation_fv_rs_bd_subnet_to_out` - (Read-Only) Relation to class l3extOut. Cardinality - N_TO_M. Type: Set of String.
```

2023-12-13 10:32 UTC, akinross commented on website/docs/r/subnet.html.markdown
> +- `ip_data_plane_learning` - (Optional) Flag to enable/disable ip-data-plane learning for the Subnet object. Allowed values are "enabled" and "disabled" and default value is "enabled". Type: String.
Could you add  Type: String. consistently behind all string inputs?

2023-12-13 10:32 UTC, akinross commented on website/docs/r/subnet.html.markdown
> +resource "aci_subnet" "foosubnet" {
Can you also update the subnet.tf example in the examples/subnet directory to include ip data plane learning?

2024-01-15 07:52 UTC, akinross approved these changes
LGTM

2024-01-15 19:23 UTC, shrsr approved these changes
LGTM

2024-01-17 01:45 UTC, merged

2024-02-04 13:04 UTC, lindie1337 commented
Thanks very much for this implementation!