Generated aci_l3out_provider_label resource and data-source files
CiscoDevNet/terraform-provider-aci pull request #1200
Opened 2024-04-15 16:08 UTC by sajagana

Note:

Generated aci_l3out_provider_label resource and data-source files and updated templates to accept parent_dependency_name from properties.yaml file

2024-04-16 05:51 UTC, akinross approved these changes
LGTM

2024-04-18 01:06 UTC, anvitha-jain submitted a review, later dismissed

2024-04-18 18:44 UTC, lhercot requested changes

2024-04-18 18:44 UTC, lhercot commented on gen/definitions/properties.yaml
> +    - "name"
Do we need those? name is a required field for those so not sure if we need this in properties.yaml.

2024-04-19 17:44 UTC, anvitha-jain approved these changes

2024-04-22 06:42 UTC, akinross approved these changes
LGTM

2024-04-22 09:06 UTC, samiib approved these changes
LGTM

2024-04-23 10:06 UTC, shrsr approved these changes
LGTM

2024-04-23 17:43 UTC, gmicol approved these changes
LGTM

2024-04-23 21:51 UTC, lhercot approved these changes
LGTM

2024-04-23 21:52 UTC, merged