Added relation_to_instance_profile resource and data-source files
CiscoDevNet/terraform-provider-aci pull request #1204
Opened 2024-04-24 17:10 UTC by sajagana

2024-04-30 22:00 UTC, gmicol approved these changes
LGTM

2024-05-06 11:58 UTC, akinross requested changes

2024-05-06 11:58 UTC, akinross commented on docs/data-sources/relation_to_instance_profile.md
> +* `target_dn` (tDn) - (string) The distinguished name of the External Network Instance Profile object.
```suggestion
* `target_dn` (tDn) - (string) The distinguished name (DN) of the External Network Instance Profile object.
```

2024-05-06 11:58 UTC, akinross commented on docs/data-sources/relation_to_instance_profile.md
> +  target_dn = aci_external_network_instance_profile.test.id
should we change these references to also state example?
```suggestion
  target_dn = aci_external_network_instance_profile.example.id
```

2024-05-06 11:58 UTC, akinross commented on docs/data-sources/relation_to_route_control_profile.md
> +* `target_dn` (tDn) - (string) The distinguished name of the Route Control Profile object.
```suggestion
* `target_dn` (tDn) - (string) The distinguished name (DN) of the Route Control Profile object.
```

2024-05-14 21:40 UTC, samiib commented
> There is a fail test for relation_to_route_control_profile data source. Do you have this error happening locally or is it a CI issue? `Error: Failed to read aci_relation_to_route_control_profile data source`

I think this is a new test that is consistently failing. I re-ran the CI and its correctly picking up the failed test.

2024-05-22 18:39 UTC, anvitha-jain requested changes
In most examples, the parent resource is missing, could you please add them either as a resource or datasource

2024-08-22 15:30 UTC, closed without merging