[bugfix] Prevent error by setting flood_on_encap and prio for aci_end…
CiscoDevNet/terraform-provider-aci pull request #1209
Opened 2024-05-02 12:56 UTC by akinross

…point_security_group

In https://github.com/CiscoDevNet/terraform-provider-aci/commit/f305774eded80334087acd613c634dda068de9a2 `flood_on_encap` and `prio` were removed from schema however in the import/create/update these values were still set. 

Which led to the following error: 

│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-aci plugin:

panic: Invalid address to set: []string{"prio"}

Cleaning up the attributes setting from the functions cleaned up the error.

2024-05-02 15:42 UTC, sajagana approved these changes
LGTM!

2024-05-03 04:10 UTC, samiib reviewed
Should the data source also still have these attributes in the schema?

2024-05-03 05:20 UTC, akinross commented
> Should the data source also still have these attributes in the schema?

Officially no, but did not want to create changes to the schema since we will be making those changes anyway soon when we are working on the migrate of the resource. But since @sajagana was also asking the same I will add the change.

2024-05-03 07:26 UTC, sajagana submitted a review, later dismissed
LGTM!

2024-05-03 20:37 UTC, gmicol submitted a review, later dismissed
LGTM

2024-05-06 16:19 UTC, anvitha-jain requested changes

2024-05-06 16:19 UTC, anvitha-jain commented on docs/data-sources/endpoint_security_group.md
> +* `annotation` - (Read-Only) Annotation of object Endpoint Security Group.
of -> of the

2024-05-06 16:19 UTC, anvitha-jain commented on docs/data-sources/endpoint_security_group.md
> +* `description` - (Read-Only) Description of object Endpoint Security Group.
of -> of the

2024-05-06 16:19 UTC, anvitha-jain commented on docs/data-sources/endpoint_security_group.md
> +* `name_alias` - (Read-Only) Name Alias of object Endpoint Security Group.
of -> of the

2024-05-06 16:19 UTC, anvitha-jain commented on docs/data-sources/endpoint_security_group.md
> +* `pref_gr_memb` - (Read-Only) Represents parameter used to determine if EPg is part of a group that does not a contract for communication.
EPg -> EPG

2024-05-06 16:19 UTC, anvitha-jain commented on legacy-docs/docs/d/endpoint_security_group.html.markdown
> +* `name` - (Required) Name of object Endpoint Security Group.
of -> of the

2024-05-06 16:19 UTC, anvitha-jain commented on legacy-docs/docs/d/endpoint_security_group.html.markdown
> +* `name_alias` - (Read-Only) Name Alias of object Endpoint Security Group.
of -> of the

2024-05-06 16:19 UTC, anvitha-jain commented on legacy-docs/docs/d/endpoint_security_group.html.markdown
> +* `pref_gr_memb` - (Read-Only) Represents parameter used to determine if EPg is part of a group that does not a contract for communication.
EPg -> EPG

2024-05-07 07:09 UTC, samiib approved these changes
LGTM

2024-05-08 01:56 UTC, shrsr approved these changes
LGTM

2024-05-08 03:52 UTC, sajagana approved these changes
LGTM!

2024-05-09 15:24 UTC, gmicol approved these changes

2024-05-14 14:16 UTC, merged