Add Resource and Datasource for Netflow Record Policy
CiscoDevNet/terraform-provider-aci pull request #1220
Opened 2024-05-23 23:09 UTC by gmicol

Resolves #1210

2024-06-10 10:26 UTC, akinross requested changes

2024-06-10 10:26 UTC, akinross commented on docs/data-sources/netflow_record_policy.md
> +* `collect` (collect) - (list) Collect parameters for the flow record.
should we change the attribute name to match UI?
```suggestion
* `collect_parameters` (collect) - (list) Collect parameters for the flow record.
```

2024-06-10 10:26 UTC, akinross commented on docs/data-sources/netflow_record_policy.md
> +* `match` (match) - (list) Match parameters for the flow record.
```suggestion
* `match_parameters` (match) - (list) Match parameters for the flow record.
```

2024-06-10 10:26 UTC, akinross commented on docs/data-sources/netflow_record_policy.md
> +* `collect` (collect) - (list) Collect parameters for the flow record.
Should we change the end of the sentence for consistency?
```suggestion
* `collect` (collect) - (list) Collect parameters of the Netflow Record Policy object.
```

2024-06-10 10:26 UTC, akinross commented on docs/data-sources/netflow_record_policy.md
> +* `match` (match) - (list) Match parameters for the flow record.
Should we change the end of the sentence for consistency?
```suggestion
* `match` (match) - (list) Match parameters of the Netflow Record Policy object.
```

2024-06-10 10:26 UTC, akinross commented on docs/resources/netflow_record_policy.md
> +terraform import aci_netflow_record_policy.example_tenant uni/infra/recordpol-{name}
How does the import work with default? Also should we provide the tenant in the example?

2024-06-14 06:57 UTC, akinross approved these changes
LGTM

2024-06-17 16:25 UTC, gmicol commented on gen/templates/resource_test.go.tmpl
> +			{{- if lt -1 (determineLength $value)}}
You're definitely right, thanks!

2024-06-17 16:51 UTC, gmicol commented on gen/templates/testvars.yaml.tmpl
> +        {{- if lt 0 (determineLength (overwritePropertyValue .PkgName $overwritePropertyName .DefaultValue "default" 0 $.Definitions))}}
I am not so sure the .ValueType is already a bitmask though. I will check the logic again.

2024-06-18 02:46 UTC, shrsr submitted a review, later dismissed
LGTM

2024-06-18 05:57 UTC, samiib submitted a review, later dismissed
LGTM!

2024-06-18 07:09 UTC, akinross submitted a review, later dismissed
LGTM

2024-06-18 15:33 UTC, anvitha-jain approved these changes

2024-06-19 23:51 UTC, lhercot requested changes

2024-06-19 23:51 UTC, lhercot commented on docs/resources/netflow_record_policy.md
> +* `collect_paramaters` (collect) - (list) Collect paramaters of the Netflow Record Policy object.
```suggestion
* `collect_parameters` (collect) - (list) Collect parameters of the Netflow Record Policy object.
```

2024-06-19 23:51 UTC, lhercot commented on gen/definitions/properties.yaml
> +    collect: "collect_paramaters"
```suggestion
    collect: "collect_parameters"
```

2024-06-19 23:51 UTC, lhercot commented on gen/definitions/properties.yaml
> +    collect: "Collect paramaters of the %s object."
```suggestion
    collect: "Collect parameters of the %s object."
```

2024-06-19 23:51 UTC, lhercot commented on gen/definitions/properties.yaml
> +    collect: "Collect paramaters of the %s object."
fix same everywhere needed

2024-06-20 22:07 UTC, anvitha-jain approved these changes

2024-06-21 03:19 UTC, samiib approved these changes
LGTM

2024-06-21 12:59 UTC, shrsr approved these changes
LGTM

2024-06-24 08:16 UTC, akinross approved these changes
LGTM

2024-06-25 20:47 UTC, lhercot approved these changes
LGTM

2024-06-25 20:50 UTC, merged