[bugfix] Add error handling in try login function for aaa_user
CiscoDevNet/terraform-provider-aci pull request #1226
Opened 2024-05-31 05:58 UTC by akinross

fixes #1216

2024-05-31 07:06 UTC, samiib submitted a review, later dismissed
LGTM

2024-05-31 15:06 UTC, anvitha-jain approved these changes

2024-06-03 11:56 UTC, sajagana requested changes

2024-06-03 11:56 UTC, sajagana commented on aci/resource_aci_aaauser.go
> +		log.Printf("[DEBUG] Authentication failed for local user: '%s'. ERROR: %s", d.Get("name").(string), err)
```suggestion
		log.Printf("[DEBUG] Authentication failed for local user: '%s'. ERROR: %v", d.Get("name").(string), err)
```

Error is not always a string.

2024-06-03 14:48 UTC, sajagana approved these changes
LGTM!

2024-06-10 16:50 UTC, anvitha-jain approved these changes

2024-06-12 11:43 UTC, samiib approved these changes
LGTM

2024-06-13 15:03 UTC, lhercot approved these changes
LGTM

2024-06-13 15:04 UTC, merged