[minor_change] Allow dn based filtering for aci_client_end_point data…
CiscoDevNet/terraform-provider-aci pull request #1229
Opened 2024-06-05 15:40 UTC by akinross

…source

fixes #513

2024-06-05 16:37 UTC, sajagana approved these changes
LGTM!

2024-06-10 17:29 UTC, anvitha-jain approved these changes
LGTM

2024-06-11 06:05 UTC, samiib submitted a review, later dismissed
LGTM

2024-06-13 15:08 UTC, lhercot requested changes

2024-06-13 15:08 UTC, lhercot commented on aci/data_source_aci_fvcep.go
> +			queryString = fmt.Sprintf("%s,wcard(fvCEp.dn, \"%s\")", queryString, filterDn.(string))
```suggestion
			queryString = fmt.Sprintf("%s,wcard(fvCEp.dn, \"%s*\")", queryString, filterDn.(string))
```

I suppose this is missing here as it is in the other else case?

2024-06-18 16:35 UTC, anvitha-jain approved these changes
LGTM

2024-06-19 22:02 UTC, samiib approved these changes
LGTM

2024-06-21 14:00 UTC, gmicol approved these changes
LGTM

2024-06-25 12:27 UTC, sajagana approved these changes
LGTM!

2024-06-25 19:24 UTC, lhercot approved these changes
LGTM

2024-06-25 19:27 UTC, merged