1165 error on create existing
CiscoDevNet/terraform-provider-aci pull request #1241
Opened 2024-06-21 08:19 UTC by akinross

fixes #1165 

requires #1223 to be merged first and then needs rebase

2024-07-02 02:51 UTC, samiib requested changes

2024-07-02 06:17 UTC, akinross commented on internal/provider/utils.go
> -				fmt.Sprintf("Code: %d Response: %s, err: %s. Please report this issue to the provider developers.", restResponse.StatusCode, cont.Data().(map[string]interface{})["imdata"], err),
No I am not suggesting that people should not raise issues anymore. 

I think this line should not have been there in the first place and is perceived as confusing. The issue lies that wrong configuration, or any other valid apic response that has nothing to do with the provider could be interpreted as raise issue with the provider. I have had people reaching out to me to report that a redirect policy was already associated with different l3outs, which does not seem like something we as provider developers should be busy with. 

Please let me know if you have a better text to put in place then I can put that there.

2024-07-02 06:20 UTC, akinross commented on internal/provider/utils.go
> +			fmt.Sprintf("The %s object with DN '%s' already exists", classname, dn),
there were more, changed those also

2024-07-02 13:27 UTC, samiib commented on internal/provider/utils.go
> -				fmt.Sprintf("Code: %d Response: %s, err: %s. Please report this issue to the provider developers.", restResponse.StatusCode, cont.Data().(map[string]interface{})["imdata"], err),
This makes sense. I thought it was something like this. Basically the message suggested it was a bug in the provider if anything goes wrong even for user config issues.

2024-07-05 14:05 UTC, sajagana approved these changes
LGTM!

2024-07-09 13:32 UTC, samiib approved these changes
LGTM

2024-07-09 15:02 UTC, lhercot approved these changes
LGTM

2024-07-09 15:03 UTC, merged