Modified functionality of DoRestRequest in utils.go to catch the appropriate errors returned by APIC
CiscoDevNet/terraform-provider-aci pull request #1264
Opened 2024-07-30 17:30 UTC by shrsr

2024-07-30 23:52 UTC, samiib requested changes

2024-07-31 20:07 UTC, shrsr commented on internal/provider/utils.go
> +				fmt.Sprintf("Err: %s. Please report this issue to the provider developers.", err),
Good call. Changed the error statement

2024-07-31 23:31 UTC, samiib approved these changes
LGTM!

2024-08-01 06:54 UTC, akinross approved these changes
LGTM

2024-08-01 18:04 UTC, anvitha-jain approved these changes
LGTM

2024-08-02 17:56 UTC, gmicol approved these changes
LGTM

2024-08-02 18:09 UTC, lhercot approved these changes
LGTM

2024-08-02 18:09 UTC, merged