[minor_change] Add resources and datasources to support qosDot1PClass and qosDscpClass and expose them in existing aci_custom_qos_policy resource and datasource as children (DCNE-35)
CiscoDevNet/terraform-provider-aci pull request #1296
Opened 2024-11-11 13:35 UTC by akinross

fixes #1267

2024-11-19 19:03 UTC, gmicol approved these changes

2024-11-19 19:09 UTC, gmicol requested changes
have you tried to see what happens with these class objects when `priority` is set to `unspecified`?

2024-11-19 21:52 UTC, shrsr requested changes

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/custom_qos_policy.md
> +  * `name` (name) - (string) The name of the Dscp To Priority Map object.
The name of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/custom_qos_policy.md
> +  * `description` (descr) - (string) The description of the Dscp To Priority Map object.
The description of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/custom_qos_policy.md
> +  * `annotation` (annotation) - (string) The annotation of the Dscp To Priority Map object.
The annotation of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/custom_qos_policy.md
> +  * `name_alias` (nameAlias) - (string) The name alias of the Dscp To Priority Map object.
The name alias of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/custom_qos_policy.md
> +  * `target` (target) - (string) Our Fabric only supports DSCP mutation. Dot1P mutation is not supported.
This Fabric only supports DSCP mutation. Dot1P mutation is not supported.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/dscp_to_priority_map.md
> +* `id` - (string) The distinguished name (DN) of the Dscp To Priority Map object.
The distinguished name (DN) of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/dscp_to_priority_map.md
> +* `annotation` (annotation) - (string) The annotation of the Dscp To Priority Map object.
The annotation of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/dscp_to_priority_map.md
> +* `description` (descr) - (string) The description of the Dscp To Priority Map object.
The description of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/dscp_to_priority_map.md
> +* `name` (name) - (string) The name of the Dscp To Priority Map object.
The name of the DSCP to the Priority Map object.

2024-11-19 21:52 UTC, shrsr commented on docs/data-sources/dscp_to_priority_map.md
> +* `name_alias` (nameAlias) - (string) The name alias of the Dscp To Priority Map object.
The name alias of the DSCP to the Priority Map object.

2024-11-20 14:34 UTC, shrsr approved these changes
LGTM

2024-11-20 18:41 UTC, gmicol submitted a review, later dismissed
LGTM

2024-11-28 16:02 UTC, sajagana requested changes

2024-11-28 17:33 UTC, shrsr submitted a review, later dismissed
LGTM

2024-11-29 06:48 UTC, sajagana submitted a review, later dismissed
LGTM!

2024-11-29 14:50 UTC, gmicol submitted a review, later dismissed
LGTM

2024-12-03 01:26 UTC, samiib approved these changes
LGTM

2025-01-06 04:01 UTC, samiib approved these changes
LGTM

2025-01-07 16:32 UTC, shrsr approved these changes
LGTM

2025-01-08 20:40 UTC, gmicol approved these changes
LGTM

2025-01-10 13:45 UTC, sajagana approved these changes
LGTM!

2025-01-24 22:23 UTC, lhercot approved these changes
LGTM

2025-01-24 22:23 UTC, merged