Added stpifpol resource, data source, examples, docs and name alias a…
CiscoDevNet/terraform-provider-aci pull request #276
Opened 2021-03-05 16:43 UTC by shrsr

…ttr schema file

2021-04-06 11:04 UTC, AshuSoni-crest commented on website/aci.erb
> -                        <a href="/docs/providers/aci/d/spine_interface_profile.html">aci_spine_interface_profile</a>
aci_spine_interface_profile index is remove, can you please add it.

2021-04-06 11:05 UTC, AshuSoni-crest commented on website/aci.erb
> +		     <li<%= sidebar_current("docs-aci-resource-spanning_tree_interface_policy") %>>
formatting is needed

2021-04-06 11:06 UTC, AshuSoni-crest requested changes
Some changes are needed.

2021-04-24 00:31 UTC, lhercot approved these changes

2021-04-24 00:31 UTC, merged