Added explanation to relationships in documentation
CiscoDevNet/terraform-provider-aci pull request #533
Opened 2021-06-28 22:55 UTC by anvitha-jain

fixes #397

2021-06-28 23:12 UTC, lhercot requested changes

2021-06-28 23:12 UTC, lhercot commented on website/docs/r/vrf.html.markdown
> +* `Location` - Tenant -> Networkinh -> VRFs
Networkinh -> Networking

2021-06-28 23:12 UTC, lhercot commented on website/docs/r/vrf.html.markdown
> +Note: In the APIC GUI,a VRF (fvCtx) is also called a "Context"or "PrivateNetwork."
I would use might/was called as we have almost changed it everywhere now. (Or should have)

2021-06-29 15:34 UTC, anvitha-jain commented on examples/bridge_domain/bd.tf
> +  relation_fv_rs_bd_flood_to     = [aci_filter.bd_flood_filter.id]  # Relation to Filters
yes

2021-06-29 16:02 UTC, anvitha-jain commented on examples/bridge_domain/bd.tf
> +  // ep_move_detect_mode            = "0"
ep_move_detect_mode  should be = "garp" and if this parameter is not required the remove the parameter (assigning to "0" will not work)

2021-06-29 20:00 UTC, lhercot approved these changes
LGTM

2021-06-29 20:00 UTC, merged