Add option to unselect garp in resource_aci_fvbd
CiscoDevNet/terraform-provider-aci pull request #709
Opened 2021-10-26 00:13 UTC by shrsr

1. Add option "disable" which unselects "garp". 
2. Though "disable" is used as the attribute, "" is being used in the payload. So "disable" is like an alias.
Example:
  ep_move_detect_mode            = ["garp"]
or
  ep_move_detect_mode            = ["disable"]

Includes updated doc and example.
Tried and tested.

2021-10-29 23:31 UTC, shrsr commented on aci/resource_aci_fvbd.go
> -			"ep_move_detect_mode": &schema.Schema{
Agreed. Made a simple fix.

2021-10-30 00:58 UTC, lhercot requested changes

2021-10-30 00:58 UTC, lhercot commented on examples/bridge_domain/bd.tf
> +  ep_move_detect_mode            = ["garp"]
This is not necessary anymore right?

2021-10-30 00:58 UTC, lhercot commented on website/docs/r/bridge_domain.html.markdown
> +		ep_move_detect_mode         = ["garp"]
Shouldn't it be
```
 ep_move_detect_mode = "garp"

2021-10-30 00:58 UTC, lhercot commented on website/docs/r/bridge_domain.html.markdown
> +## Argument Reference ##
Why all those changes?

2021-10-30 00:58 UTC, lhercot commented on website/docs/r/bridge_domain.html.markdown
> +Allowed values: "garp" and "disable". Default is "disable". Type - List.
Not type list anymore

2021-10-30 14:58 UTC, shrsr commented on examples/bridge_domain/bd.tf
> +  ep_move_detect_mode            = ["garp"]
Yes

2021-10-30 14:58 UTC, shrsr commented on website/docs/r/bridge_domain.html.markdown
> +		ep_move_detect_mode         = ["garp"]
Yes

2021-10-30 14:59 UTC, shrsr commented on website/docs/r/bridge_domain.html.markdown
> +## Argument Reference ##
Reverted

2021-10-30 14:59 UTC, shrsr commented on website/docs/r/bridge_domain.html.markdown
> +Allowed values: "garp" and "disable". Default is "disable". Type - List.
Yes

2021-11-02 21:45 UTC, lhercot approved these changes
LGTM

2021-11-02 21:47 UTC, merged