Added module to manage InfraRsDomP class
CiscoDevNet/terraform-provider-aci pull request #824
Opened 2022-03-14 17:07 UTC by sajagana

Note:

Added module to manage Attachable Access Entity Profile - domain interfaces

2022-03-15 23:49 UTC, shrsr commented on aci/data_source_aci_infrarsdomp.go
> +	tDn := d.Get("tDn").(string)
Isn't this supposed to be t_dn?

2022-03-15 23:52 UTC, shrsr commented on website/docs/r/aci_aaep_to_domain.html.markdown
> +terraform import aci_domain.example <Dn>
terraform import aci_aaep_to_domain.example <Dn>

2022-03-15 23:55 UTC, shrsr reviewed
Please make changes.

2022-03-18 17:35 UTC, anvitha-jain approved these changes
LGTM

2022-03-23 01:52 UTC, lhercot requested changes

2022-03-23 01:52 UTC, lhercot commented on aci/resource_aci_infrarsdomp.go
> +			"t_dn": {
domain_dn

2022-03-23 01:52 UTC, lhercot commented on aci/resource_aci_infrarsdomp.go
> +			"annotation": {
Due to annotation being a optional / modifiable attribute, you will need to add an update function.

2022-03-23 01:52 UTC, lhercot commented on examples/aci_aaep_to_domain/main.tf
> +}
Those outputs are not needed in the example

2022-03-23 01:52 UTC, lhercot commented on examples/aci_aaep_to_domain/main.tf
> +}
This one also not needed.

2022-03-23 01:52 UTC, lhercot commented on examples/aci_aaep_to_domain/main.tf
> +}
This one also not needed.

2022-03-23 01:52 UTC, lhercot commented on examples/aci_aaep_to_domain/main.tf
> +  name_alias = "example"
remove those as they are not needed for this example.

2022-03-23 01:52 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `Location` - Attachable Access Entity Profile -> Domains Associated to Interfaces
AAEPs are under Fabric -> Access Policies -> Policies -> Global -> AAEP

2022-03-23 01:52 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `Location` - Attachable Access Entity Profile -> Domains Associated to Interfaces
AAEPs are under Fabric -> Access Policies -> Policies -> Global -> AAEP

2022-03-23 01:52 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `t_dn` - (Optional) Target-dn.The virtual machine manager domain profile.
domain_dn. The Distringuished Name of a domain.

2022-03-23 21:09 UTC, lhercot requested changes

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +Data source for ACI Attachable Access Entity Profile - VMM, Physical or External domain interfaces.
Data source for ACI Attachable Access Entity Profile (AAEP) to domain (VMM, Physical or External domain) relationships.

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `Distinguished Name` - uni/infra/attentp-{name}/rsdomP-[{tDn}]
name -> aaep_name
tDn -> domain_dn

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `attachable_access_entity_profile_dn` - (Required) Distinguished name of parent AttachableAccessEntityProfile object.
of the parent Attachable Access Entity Profile object.

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `annotation` - (Optional) Annotation of the object Domain.
not a necessary argument so can be removed from here and is documented in the attribute section.

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `domain_dn` - (Required) TDn of object Domain.
The Distinguished name of the domain object.

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `id` - Attribute id set to the Dn of the Domain.
of the Attachable AccessEntity Profile to Domain Relationship object

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `annotation` - (Optional) Annotation of object Domain.
of the Attachable AccessEntity Profile to Domain Relationship object

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +* `domain_dn` - (Optional) Target-dn. The virtual machine manager domain profile.
remove as already provided as argument

2022-03-23 21:09 UTC, lhercot commented on website/docs/d/aaep_to_domain.html.markdown
> +  Data source for ACI Attachable Access Entity Profile - VMM, Physical or External domain interfaces.
Data source for ACI Attachable Access Entity Profile (AAEP) to domain (VMM, Physical or External domain) relationships.

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +  Manages ACI Attachable Access Entity Profile - VMM, Physical or External domain interfaces.
Manages the ACI Attachable Access Entity Profile (AAEP) to domain (VMM, Physical or External domain) relationship

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +Manages ACI Attachable Access Entity Profile  - VMM, Physical or External domain interfaces.
Manages the ACI Attachable Access Entity Profile (AAEP) to domain (VMM, Physical or External domain) relationship

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `Distinguished Name` - uni/infra/attentp-{name}/rsdomP-[{tDn}]
name -> aaep_name
tDn -> domain_dn

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `attachable_access_entity_profile_dn` - (Required) Distinguished name of the parent AttachableAccessEntityProfile object.
of the parent Attachable Access Entity Profile object.

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `annotation` - (Optional) Annotation of the object Domain.
of the Attachable AccessEntity Profile to Domain Relationship object

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +* `domain_dn` - (Optional) Target-dn.The virtual machine manager domain profile.
(Required) The Distinguished name of the domain object.

2022-03-23 21:09 UTC, lhercot commented on website/docs/r/aaep_to_domain.html.markdown
> +An existing Domain can be [imported][docs-import] into this resource via its Dn, via the following command:
An existing Attachable Access Entity Profile to Domain Relationship object can ...

2022-03-23 21:11 UTC, lhercot requested changes
Also don't forget to get the latest go client and commit the files to this PR.

```
go get github.com/ciscoecosystem/aci-go-client@v1.xx.y
go mod vendor
```

2022-03-24 16:39 UTC, anvitha-jain requested changes

2022-03-24 16:39 UTC, anvitha-jain commented on examples/aci_aaep_to_domain/main.tf
> +resource "aci_attachable_access_entity_profile" "fooattachable_access_entity_profile" {
change fooattachable_access_entity_profile -> foo_attachable_access_entity_profile

2022-03-24 16:39 UTC, anvitha-jain commented on examples/aci_aaep_to_domain/main.tf
> +resource "aci_l3_domain_profile" "fool3_domain_profile" {
change fool3_domain_profile -> foo_l3_domain_profile

2022-03-24 16:39 UTC, anvitha-jain commented on go.mod
> +replace github.com/ciscoecosystem/aci-go-client => /Users/sajagana/go/src/github.com/ciscoecosystem/aci-go-client
This line can be removed, it is only for local use.

2022-03-24 16:39 UTC, anvitha-jain commented on go.sum
>  github.com/ciscoecosystem/aci-go-client v1.25.0/go.mod h1:pGK3tDhR/D4+P5f6utT1V7TQQxDw2fL7j79QXeVk6po=
Remove line 68 and 69, older versions are not required.

2022-03-24 19:23 UTC, lhercot commented
You probably also just want to rebase it on latest master

2022-03-25 21:26 UTC, lhercot approved these changes
LGTM

2022-03-25 21:31 UTC, anvitha-jain approved these changes
LGTM

2022-03-25 21:33 UTC, merged