[aci_epg_to_contract_interface] Added new resource fv_rs_cons_if .
CiscoDevNet/terraform-provider-aci pull request #833
Opened 2022-03-22 17:46 UTC by anvitha-jain

Made changes to examples files so that they can run on their own. solves #812

2022-03-23 18:04 UTC, lhercot requested changes

2022-03-23 18:04 UTC, lhercot commented on website/docs/r/fvrsconsif.html.markdown
> +* `Distinguished Name` - uni/tn-{name}/ap-{name}/epg-{name}/rsconsIf-{tnVzCPIfName}
tnVzCPIfName -> contract_interface_name

2022-03-23 18:04 UTC, lhercot commented on website/docs/d/fvrsconsif.html.markdown
> +* `Distinguished Name` - uni/tn-{name}/ap-{name}/epg-{name}/rsconsIf-{tnVzCPIfName}
tnVzCPIfName -> contract_interface_name

2022-03-23 18:04 UTC, lhercot commented on website/docs/r/fvrsconsif.html.markdown
> +  tnVzCPIfName  = "example"
Update this too

2022-03-23 18:04 UTC, lhercot commented on website/docs/r/fvrsconsif.html.markdown
> +* `tnVzCPIfName` - (Required) TnVzCPIfName of the object Contract Interface.
Update this too

2022-03-23 20:42 UTC, lhercot requested changes

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `application_epg_dn` - (Required) Distinguished name of the parent ApplicationEPG object.
Application EPG

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `annotation` - (Optional) Annotation of the object Contract Interface.
of the Contract Interface Relationship object

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of the object Contract Interface.
of the Contract Interface object

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `prio` - (Optional) prio.The contract interface priority. Allowed values are "level1", "level2", "level3", "level4", "level5", "level6", "unspecified", and default value is "unspecified". Type: Str
(Optional) The Contract Interface Relationship priority. ...

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +An existing ContractInterface can be [imported][docs-import] into this resource via its Dn, via the following command:
An existing Contract Interface Relationship object can be...

2022-03-23 20:42 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +terraform import aci_contract_interface.example <Dn>
aci_epg_to_contract_interface

2022-03-23 20:42 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +Data source for ACI Contract Interface
for ACI Contract Interface Relationship

2022-03-23 20:42 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +data "aci_contract_interface" "example" {
aci_epg_to_contract_interface

2022-03-23 20:42 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `application_epg_dn` - (Required) Distinguished name of parent ApplicationEPG object.
Application EPG

2022-03-23 20:42 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of object Contract Interface.
of the Contract Interface object

2022-03-24 16:51 UTC, lhercot requested changes

2022-03-24 16:51 UTC, lhercot commented on aci/resource_aci_fvrsconsif.go
> +	d.Set("application_epg_dn", GetParentDn(dn, fmt.Sprintf("/"+models.RnfvRsConsIf, fvRsConsIfMap["tnVzCPIfName"])))
add spaces around the +

2022-03-24 16:51 UTC, lhercot commented on aci/resource_aci_fvrsconsif.go
> +	ApplicationEPGDn := d.Get("application_epg_dn").(string)
applicationEpgDn

2022-03-24 16:51 UTC, lhercot commented on aci/resource_aci_fvrsconsif.go
> +	ApplicationEPGDn := d.Get("application_epg_dn").(string)
applicationEpgDn

2022-03-24 16:51 UTC, lhercot commented on aci/resource_aci_rtctrlattrp.go
This should be fixed on latest master. Remove that change and rebase on top of master.

2022-03-24 16:51 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `application_epg_dn` - (Required) Distinguished name of parent Application EPG object.
of the parent

2022-03-24 16:51 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of object Contract Interface object.
of the Contract...

2022-03-24 16:51 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `annotation` - (Optional) Annotation of object Contract Interface Relationship object.
of the Contract...

2022-03-24 16:51 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of the object Contract Interface object.
remove first object
the Contract...

2022-03-24 16:51 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `annotation` - (Optional) Annotation of the object Contract Interface Relationship object.
remove first object
the Contract...

2022-03-24 16:51 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `prio` - (Optional) The contract interface priority. Allowed values are "level1", "level2", "level3", "level4", "level5", "level6", "unspecified", and default value is "unspecified". Type: String.
(Optional) The Contract Interface Relationship priority. Allowed...

2022-03-24 18:57 UTC, lhercot requested changes

2022-03-24 18:57 UTC, lhercot commented on website/docs/d/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of object Contract Interface object.
this is not fixed

2022-03-24 18:57 UTC, lhercot commented on website/docs/r/epg_to_contract_interface.html.markdown
> +* `contract_interface_dn` - (Required) Distinguished name of the object Contract Interface object.
still not fixed

2022-03-24 18:58 UTC, anvitha-jain commented on aci/resource_aci_fvrsconsif.go
> +	d.Set("application_epg_dn", GetParentDn(dn, fmt.Sprintf("/"+models.RnfvRsConsIf, fvRsConsIfMap["tnVzCPIfName"])))
fmt doesn't allow this

2022-03-24 19:09 UTC, lhercot approved these changes
LGTM

2022-03-24 19:09 UTC, merged