[minor_change] Add custom_epg_name attribute to resource "aci_epg_to_domain"
CiscoDevNet/terraform-provider-aci pull request #841
Opened 2022-04-12 07:47 UTC by shrsr

2022-04-12 18:41 UTC, lhercot requested changes
Update example and documentation

2022-04-14 17:08 UTC, xinyuezhao submitted a review, later dismissed

2022-04-14 17:08 UTC, xinyuezhao commented on go.sum
> +github.com/ciscoecosystem/aci-go-client v1.33.0 h1:/DegzYxTGQrA0C9zMVN50OKqSKW4RkjrQbzP8jK4mFI=
you may want to remove aci-go-client v1.31.0

2022-04-14 18:14 UTC, lhercot requested changes
Seems the new vendor files are missing. Can you make sure you do `go mod vendor` and commit the changed files?

2022-04-14 18:14 UTC, lhercot commented on website/docs/r/epg_to_domain.html.markdown
> +* `custom_epg_name` - (Optional) Custom Epg name for object Domain.
Custom EPG name used as name of the VMM port group for the domain.

2022-04-18 15:19 UTC, anvitha-jain reviewed
Everywhere in resource and datasource files, where  -> ("rsdomAtt-[%s]", tDn) is present shouldn't it be replaced by thr Rnattribute?

2022-04-26 15:36 UTC, shrsr commented
@anvitha-jain For this particular resource we don't have RN defined as a constant on SDK, so it should remain ("rsdomAtt-[%s]", tDn)

2022-04-27 21:24 UTC, lhercot approved these changes
LGTM

2022-04-27 21:25 UTC, merged