Addition of resource and data source for vnsRedirectHealthGroup
CiscoDevNet/terraform-provider-aci pull request #877
Opened 2022-05-31 21:27 UTC by shrsr

2022-05-31 22:43 UTC, lhercot requested changes

2022-05-31 22:43 UTC, lhercot commented on examples/redirect_health_group/main.tf
> +}
Can you also add this section in the example of aci_destination_of_redirected_traffic ?

2022-05-31 22:43 UTC, lhercot commented on website/docs/r/redirect_health_group.html.markdown
> +* `annotation` - (Optional) Annotation of the L4-L7 Redirect Health Group object.
where is the description and name_alias?

2022-05-31 22:45 UTC, shrsr commented on website/docs/d/redirect_health_group.html.markdown
> +subcategory: "Tenant Policies"
ok

2022-05-31 22:45 UTC, shrsr commented on website/docs/r/redirect_health_group.html.markdown
> +subcategory: "Tenant Policies"
ok

2022-06-01 02:12 UTC, lhercot requested changes

2022-06-01 02:12 UTC, lhercot commented on aci/resource_aci_vnsredirecthealthgroup.go
> +		return nil, fmt.Errorf("L4 L7Redirect Health Group %s not found", dn)
L4-L7 Redirect Health Group %s not found

2022-06-01 02:12 UTC, lhercot commented on aci/resource_aci_vnsredirecthealthgroup.go
> +		d.Set("tenant_dn", strings.Split(GetParentDn(vnsRedirectHealthGroup.DistinguishedName, fmt.Sprintf("/"+models.RnvnsRedirectHealthGroup, vnsRedirectHealthGroupMap["name"])), "/svcCont")[0])
if you are splitting on /svcCont, you probably don't need the GetParentDn. You can either use split or use GetParentDn twice.

2022-06-01 02:12 UTC, lhercot commented on examples/redirect_health_group/main.tf
> +  url      = "" # <cloud APIC URL>
APIC URL (remove cloud)

2022-06-04 07:39 UTC, lhercot approved these changes
LGTM

2022-06-04 07:40 UTC, merged