The data source for the object: vnsEPGDef
CiscoDevNet/terraform-provider-aci pull request #884
Opened 2022-06-04 13:33 UTC by shrsr

2022-06-06 17:06 UTC, anvitha-jain reviewed
Do we have an example for data source for this object?

2022-06-07 12:00 UTC, sajagana commented on website/docs/d/epg_def.html.markdown
> +* `Distinguished Name` - uni/tn-{name}/GraphInst_C-[{ctrctDn}]-G-[{graphDn}]-S-[{scopeDn}]/NodeInst-{name}/LegVNode-{name}/EPgDef-{name}
Please used different values instead of "name" like(tenant_name, etc).

It is good to have if the "GUI Information" is available.

2022-06-10 20:24 UTC, lhercot requested changes

2022-06-10 20:24 UTC, lhercot commented on website/docs/d/l4_l7_deployed_graph_connector_vlan.html.markdown
> +  Data source for ACI EPg Def
Data Source for ACI L4-L7 Deployed Graph Connector VLAN

2022-06-10 20:24 UTC, lhercot commented on website/docs/d/l4_l7_deployed_graph_connector_vlan.html.markdown
> +Data source for ACI EPg Def
Data Source for ACI L4-L7 Deployed Graph Connector VLAN

2022-06-10 20:24 UTC, lhercot commented on website/docs/d/l4_l7_deployed_graph_connector_vlan.html.markdown
> +## Example Usage ##
Add UI location

2022-06-12 00:50 UTC, lhercot approved these changes
LGTM

2022-06-12 00:51 UTC, merged