[minor_change] Allow nil return option for datasource client_end_point
CiscoDevNet/terraform-provider-aci pull request #893
Opened 2022-06-14 11:08 UTC by akinross

fixes #850

2022-06-22 17:32 UTC, lhercot requested changes

2022-06-22 17:32 UTC, lhercot commented on examples/client_end_point/main.tf
> +  mac                         = "${data.aci_client_end_point.check.fvcep_objects.0.mac}"
I think you can do:
mac = data.aci_client_end_point.check.fvcep_objects.0.mac
(same for .ip)

2022-06-23 07:56 UTC, akinross commented on aci/utils.go
> +func allowEmpty(e error, a bool) error {
ok agree

2022-06-24 00:29 UTC, lhercot approved these changes
LGTM

2022-06-24 00:30 UTC, merged