create resource aci_bulk_epg_to_static_path
CiscoDevNet/terraform-provider-aci pull request #896
Opened 2022-06-27 17:30 UTC by xinyuezhao

- create resource aci_bulk_epg_to_static_path which allow multiple static path to be created in one api call
- create example tf plan for this resource

2022-07-20 22:24 UTC, lhercot requested changes

2022-07-20 22:24 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +		url += "?rsp-subtree=children"
https://{{APIC1_PUB_IP}}/api/mo/uni/tn-sabari-test/ap-sabari-app-test/epg-test-epg.json?rsp-subtree=children&rsp-subtree-class=fvRsPathAtt
https://{{APIC1_PUB_IP}}/api/class/uni/tn-sabari-test/ap-sabari-app-test/epg-test-epg/fvRsPathAtt.json
https://{{APIC1_PUB_IP}}/api/mo/uni/tn-sabari-test/ap-sabari-app-test/epg-test-epg.json?query-target=children&target-subtree-class=fvRsPathAtt

2022-07-20 22:24 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +		log.Printf("[DEBUG]: primaryEncap in staticPathPayload %s", staticPath["primary_encap"])
not needed

2022-07-26 00:48 UTC, xinyuezhao commented on aci/resource_aci_fvrsbulkpathatt.go
> +	d.Get("static_path").(*schema.Set).List()
removed

2022-07-26 00:51 UTC, xinyuezhao commented on aci/resource_aci_fvrsbulkpathatt.go
> +	return bulkStaticPath, nil
removed

2022-07-26 01:56 UTC, xinyuezhao commented on aci/resource_aci_fvrsbulkpathatt.go
> +func bulkStaticPathRequest(aciClient *client.Client, method string, path string, body *container.Container) (*container.Container, diag.Diagnostics) {
epgDn

2022-07-26 01:56 UTC, xinyuezhao commented on aci/resource_aci_fvrsbulkpathatt.go
> +		url += "?rsp-subtree=children"
pick the third one

2022-07-27 21:38 UTC, lhercot requested changes

2022-07-27 21:38 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +func getAciBulkStaticPath(aciClient *client.Client, dn string) ([]interface{}, diag.Diagnostics) {
Is this returning 1 or more static paths? If more than one, rename the function to getAciBulkStaticPaths

2022-07-27 21:38 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +}
not needed. use getOldObjectsNotInNew("interface_dn", oldSet, newSet)

2022-07-27 21:38 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +		log.Printf("[DEBUG]: primaryEncap in staticPathPayload %s", staticPath["primary_encap"])
remove

2022-07-27 21:38 UTC, lhercot commented on aci/resource_aci_fvrsbulkpathatt.go
> +	d = setAciBulkStaticPath(bulkStaticPath, d)
don't think this is needed.

2022-07-27 21:38 UTC, lhercot commented on examples/aci_bulk_epg_to_static_path/main.tf
> +terraform {
run terraform fmt to reformat it.

2022-07-27 23:07 UTC, lhercot approved these changes
LGTM

2022-07-27 23:12 UTC, merged