[ignore] Initial commit
CiscoDevNet/terraform-provider-aci pull request #912
Opened 2022-07-28 16:09 UTC by anvitha-jain

solves #545

2022-07-29 19:47 UTC, lhercot requested changes

2022-07-29 19:47 UTC, lhercot commented on aci/resource_aci_cloudaccount.go
> +		}
shouldn't there be a condition on the recreation? What happens if the relationship is not defined anymore?

2022-07-29 19:47 UTC, lhercot commented on aci/resource_aci_cloudaccount.go
> +func resourceAciAccountRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
resourceAciAccountRead -> resourceAciCloudAccountRead

2022-07-29 19:47 UTC, lhercot commented on aci/resource_aci_cloudaccount.go
> +		// d.SetId("")
do we need this line?

2022-07-29 19:47 UTC, lhercot commented on aci/resource_aci_cloudaccount.go
> +		// d.SetId("")
do we need this line?

2022-07-29 19:47 UTC, lhercot commented on aci/resource_aci_cloudaccount.go
> +			}
Remove this part

2022-07-29 19:47 UTC, lhercot commented on examples/cloud_azure_account/main.tf
> +  url      = "https://104.42.26.226/"
Clean this

2022-07-29 19:47 UTC, lhercot commented on examples/cloud_azure_account/main.tf
> +  name_alias  = "alias_tenant"
don't need those in this example

2022-07-29 19:47 UTC, lhercot commented on examples/cloud_azure_account/main.tf
> +  account_id        = "test123"
use somehting like my_example_account_id or something

2022-07-29 19:47 UTC, lhercot commented on examples/cloud_azure_account/main.tf
> +  # description       = "zure account config"
zure?

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +layout: "aci"
add subcategory

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +# aci_account #
aci_cloud_account

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +  Data source for ACI Account
ACI Cloud Account

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +Data source for ACI Account
ACI Cloud Account

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `Location` -
Add UI location

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `tenant_dn` - (Required) Distinguished name of parent Tenant object.
of the parent Tenant object

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `account_id` - (Required) Account_id of object Account.
ID of the Cloud Account object

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `vendor` - (Required) Vendor of object Account.
Vendor of the Cloud Account object

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `id` - Attribute id set to the Dn of the Account.
of the Cloud Account

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `annotation` - (Optional) Annotation of object Account.
of the Cloud Account object

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `name_alias` - (Optional) Name Alias of object Account.
of the Cloud Account object

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `access_type` - (Optional) Account acccess type. How to authenticate to the account (managed=no credentials required (IAM), credentials=using accessKeys)
I am not a fan of the second part can you rephrase it.

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `account_id` - (Optional) Account id. An object identifier.
remove it from here as part of required attribute

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `vendor` - (Optional) Account vendor. The vendor of the controller.
remove it from here as part of required attribute

2022-07-29 19:47 UTC, lhercot commented on website/docs/d/cloud_azure_account.html.markdown
> +* `Distinguished Name` - uni/tn-{name}/act-[{id}]-vendor-{vendor}
name -> tenant_name
id -> account_id

2022-07-29 19:47 UTC, lhercot commented on website/docs/r/cloud_azure_account.html.markdown
> +---
Apply same comments as from data source

2022-07-30 00:05 UTC, anvitha-jain commented on aci/resource_aci_cloudaccount.go
> +					"managed",
It is only 2 in azure

2022-08-03 23:53 UTC, lhercot requested changes

2022-08-03 23:53 UTC, lhercot commented on aci/resource_aci_fvrscloudaccount.go
> +		return nil, fmt.Errorf("TenanttoCloudAccountAssociation %s not found", fvRsCloudAccount.DistinguishedName)
Tenant to Cloud Account Association %s

2022-08-03 23:53 UTC, lhercot commented on examples/aci_cloud_account/main.tf
> +terraform {
Merge all into a single example

2022-08-03 23:53 UTC, lhercot commented on website/docs/d/cloud_account.html.markdown
> +* `Location` - Cloud APIC -> Application Management -> Tenants
Cloud APIC -> Application Management -> Tenants -> {tenant_name}

2022-08-03 23:53 UTC, lhercot commented on website/docs/d/cloud_account.html.markdown
> +* `access_type` - (Optional) Authentication to the Cloud Account (managed=no credentials required (IAM), credentials=using accessKeys).
Authentication type for the Cloud Account

2022-08-03 23:53 UTC, lhercot commented on website/docs/d/tenant_to_cloud_account.html.markdown
> +* `Location` - Cloud APIC -> Application Management -> Tenants
Cloud APIC -> Application Management -> Tenants -> {tenant_name}

2022-08-03 23:53 UTC, lhercot commented on website/docs/d/tenant_to_cloud_account.html.markdown
> +* `cloud_account_dn` - (Optional) Target-dn. The distinguished name of the target Tenant's Cloud Account object.
(Optional) The distinguished name of the target Cloud Account object.

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `Location` - Cloud APIC -> Application Management -> Tenants
Cloud APIC -> Application Management -> Tenants -> {tenant_name}

2022-08-03 23:53 UTC, lhercot commented on website/docs/d/tenant_to_cloud_account.html.markdown
> +  cloud_account_dn = aci_cloud_account_example.id
aci_cloud_account.example.id

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +  vendor  = "example"
example is not a correct vendor

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +  account_id = "example"
why is account_id and vendor twice?

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +  cloud_rs_account_to_access_policy = aci_resource.example.id
put one of the dn of the access policy as we don't have a resource for it.

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +  cloud_rs_credentials = aci_resource.example.id
aci_cloud_credentials.example.id

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `vendor` - (Required) Vendor of the Cloud Account object.
is there allowed values for vendor?

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `vendor` - (Required) Vendor of the Cloud Account object.
Copy text from optional vendor attribute

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `vendor` - (Optional) The Cloud Account vendor of the controller. Allowed values are "aws", "azure", "gcp", "unknown", and default value is "aws". Type: String.
why twice?

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `access_type` - (Optional) Authentication to the Cloud Account (managed=no credentials required (IAM), credentials=using accessKeys). Allowed values are "credentials", "managed". Default value is "
Authentication type for the Cloud Account

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/tenant_to_cloud_account.html.markdown
> +* `Location` - Cloud APIC -> Application Management -> Tenants
Cloud APIC -> Application Management -> Tenants -> {tenant_name}

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/tenant_to_cloud_account.html.markdown
> +  cloud_account_dn = aci_cloud_account_example.id
aci_cloud_account.example.id

2022-08-03 23:53 UTC, lhercot commented on website/docs/r/tenant_to_cloud_account.html.markdown
> +* `cloud_account_dn` - (Optional) Target-dn. The distinguished name of the target Tenant's Cloud Account object.
(Optional) The distinguished name of the target Cloud Account object.

2022-08-26 00:57 UTC, lhercot requested changes

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +Note: This resource is supported in Cloud APIC only.
We probably want this note in the other ones too.
It is a datasource here though

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `name` - (Required) Name of the Access Credential object used to manage the cloud resources.
Name of the Cloud Credentials object used...

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `id` - Attribute id set to the Dn of the Access Credential to manage the cloud resources.
of the Cloud Credentials object.

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `annotation` - (Optional) Annotation of the Access Credential object to manage the cloud resources.
of the Cloud Credentials object.

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `name_alias` - (Optional) Name Alias of the Access Credential object to manage the cloud resources.
of the Cloud Credentials object.

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `client_id` - (Optional) Client ID of the Access Credential object.
of the Cloud Credentials object.

2022-08-26 00:57 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `http_proxy` - (Optional) Http Proxy to connect to cloud provider.
used to connect to the cloud provider

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `access_type` - (Optional) Authentication type for the Cloud Account (managed=no credentials required (IAM), credentials=using accessKeys). Allowed values are "credentials", "managed". Type: String
are "credentials" and "managed"

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `vendor` - (Required) Vendor of the Cloud Account object. Allowed values are "aws", "azure", "gcp", "unknown". Type: String.
and "unknown".

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `relation_cloud_rs_account_to_access_policy` - (Optional) Represents the relation to a Relation to the Access policy to be used (class cloudAccessPolicy). Relation to CloudAccessPolicy cardianity i
Represents the relation to the Access policy to be used (class cloudAccessPolicy). Type: String.

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloud_account.html.markdown
> +* `relation_cloud_rs_credentials` - (Optional) Represents the relation to a Credentials to use to manage the account (class cloudCredentials). If access type is credentials, relation to the credentia
to Cloud Credentials to use ...
If the access_type is  credentials, this relation attribute is required. Type: String.

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudad.html.markdown
> +  Manages Cloud ACI Active Directory
ACI Cloud Active Directory

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudad.html.markdown
> +Manages Cloud ACI Active Directory
ACI Cloud Active Directory

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudad.html.markdown
> +
remove empty line

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudad.html.markdown
> +* `active_directory_id` - (Required) Active_directory_id of the object Active Directory.
(Required) Id of the Azure Active Directory.

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudcredentials.html.markdown
> +* `annotation` - (Optional) Annotation of the Access Credential object to manage the cloud resources.
of the Cloud Credentials object used to manage the cloud resources.

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudcredentials.html.markdown
> +* `name` - (Required) Name of the Access Credential object to manage the cloud resources.
of the Cloud Credentials object used to manage the cloud resources.

2022-08-26 00:57 UTC, lhercot commented on website/docs/r/cloudcredentials.html.markdown
> +* `http_proxy` - (Optional) Http Proxy to connect to cloud provider.
to the cloud provider

2022-08-26 20:54 UTC, lhercot requested changes

2022-08-26 20:54 UTC, lhercot commented on aci/resource_aci_cloudcredentials.go
> +
remove empty line

2022-08-26 20:54 UTC, lhercot commented on website/docs/d/cloud_credentials.html.markdown
> +* `http_proxy` - (Optional) Http Proxy to connect to the cloud provider.
HTTP Proxy

2022-08-26 20:54 UTC, lhercot commented on website/docs/r/cloudcredentials.html.markdown
> +* `rsa_private_key` - (Optional)  RSA Secret Key of the cloud resource. Allowed values are and default value is "".
I think the allowed value part can be removed as it is empty.

2022-10-06 05:21 UTC, lhercot approved these changes
LGTM

2022-10-06 15:42 UTC, lhercot approved these changes
LGTM

2022-10-06 15:44 UTC, merged