[minor_change] Removed "Required" condition for mac attribute
CiscoDevNet/terraform-provider-aci pull request #951
Opened 2022-10-18 07:53 UTC by shrsr

2022-10-19 01:02 UTC, lhercot requested changes

2022-10-19 01:02 UTC, lhercot commented on website/docs/d/destination_of_redirected_traffic.html.markdown
> +- `dest_name` - (Optional) The destination name to which data was exported.
I don't think those descriptions are correct.

2022-10-19 01:02 UTC, lhercot commented on website/docs/r/destination_of_redirected_traffic.html.markdown
> +- `mac` - (Optional) The MAC address. This is a required value for APIC prior to Version 5.2 release. This value can be foregone by enabling IPSLA on APIC Version 5.2 and above due to dynamic mac det
Version -> version

2022-10-19 01:02 UTC, lhercot commented on website/docs/r/destination_of_redirected_traffic.html.markdown
> +- `dest_name` - (Optional) The destination name to which the data was exported.
I don't think this description is clear

2022-10-19 18:03 UTC, anvitha-jain requested changes

2022-10-19 18:03 UTC, anvitha-jain commented on website/docs/d/destination_of_redirected_traffic.html.markdown
> +- `ip2` - (Optional) IP2 for the object destination of redirected traffic.
IP2 for the object destination of redirected traffic. -> IP2 of the destination of redirected traffic object.

2022-10-19 18:03 UTC, anvitha-jain commented on website/docs/d/destination_of_redirected_traffic.html.markdown
> +- `name_alias` - (Optional) Name alias for the object destination of redirected traffic.
Name alias for the object destination of redirected traffic. -> Name alias of the destination of redirected traffic object.

2022-10-19 18:03 UTC, anvitha-jain commented on website/docs/r/destination_of_redirected_traffic.html.markdown
> +- `description` - (Optional) Description for the object destination of redirected traffic.
for the object destination of redirected traffic -> of the destination of redirected traffic object.

2022-10-20 09:52 UTC, shrsr commented on website/docs/d/destination_of_redirected_traffic.html.markdown
> +- `dest_name` - (Optional) The destination name to which data was exported.
Changed them

2022-10-20 22:35 UTC, lhercot approved these changes
LGTM

2022-10-21 15:15 UTC, anvitha-jain approved these changes
LGTM

2022-10-21 17:46 UTC, merged