Added Service Redirect Backup Policy and L1/L2 Destination resources
CiscoDevNet/terraform-provider-aci pull request #965
Opened 2022-11-18 07:35 UTC by sajagana

Note:

Added Service Redirect Backup Policy and L1/L2 Destination resources
Created a common example file for Service Redirect Policy and Service Redirect Backup Policy

2022-12-02 08:38 UTC, akinross commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `relation_vns_rs_l1_l2_redirect_health_group` - (Optional) Represents the relation to a L4-L7 Redirect Health Group (class vnsRedirectHealthGroup). Type: String.
When argument is of type string is "Type: String" needed in the text? Applies for the other documentation also in this PR.

2022-12-02 08:41 UTC, akinross commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `dest_name` - (Required) Destination Name of the L1/L2 redirected traffic.
Do we need object(s) appended to L1/L2 redirected traffic? And capitalise R and T?

2023-01-05 21:13 UTC, anvitha-jain requested changes

2023-01-05 21:13 UTC, anvitha-jain commented on website/docs/r/service_redirect_backup_policy.html.markdown
> +An existing PBRBackupPolicy can be [imported][docs-import] into this resource via its Dn, via the following command:
PBRBackupPolicy -> PBR Backup Policy

2023-01-12 23:03 UTC, lhercot requested changes

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `id` - Attribute id set to the Dn of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `annotation` - (Optional) Annotation of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `name_alias` - (Optional) Name Alias of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `name` - (Optional) Name of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `mac` - (Optional) MAC Address of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `pod_id` - (Optional) Pod Id of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/d/pbr_l1_l2_destination.html.markdown
> +* `policy_based_redirect_dn` - (Required) Distinguished name of the parent Policy-Based Redirect object.
Distinguished name of the parent Policy-Based (Redirect or Redirect Backup) object

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `dest_name` - (Required) Destination Name of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `annotation` - (Optional) Annotation of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `name_alias` - (Optional) Name Alias of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `name` - (Optional) Name of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `mac` - (Optional) MAC Address of the L1/L2 Redirected Traffic.
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +* `pod_id` - (Optional) Pod Id of the L1/L2 Redirected Traffic. Allowed range is 1-255 and default value is "1".
of the destination of the L1/L2 Redirected Traffic.

2023-01-12 23:03 UTC, lhercot commented on website/docs/r/pbr_l1_l2_destination.html.markdown
> +An existing L1/L2 Redirected Traffic can be [imported][docs-import] into this resource via its Dn, via the following command:
An existing Destination of the L1/L2 Redirected Traffic...

2023-01-17 09:47 UTC, lhercot approved these changes
LGTM

2023-01-17 09:54 UTC, akinross approved these changes
LGTM

2023-01-17 09:58 UTC, merged