Note:  Fixed resource_aci_l3extout idempotency issue and relationship attribute import issues
CiscoDevNet/terraform-provider-aci pull request #973
Opened 2022-12-09 15:42 UTC by sajagana

Note:

Fixed resource_aci_l3extout idempotency issue and relationship attribute import issues.

2022-12-13 17:21 UTC, anvitha-jain requested changes

2022-12-14 07:48 UTC, akinross commented on aci/data_source_aci_l3extout.go
> +				Type:     schema.TypeString,
You are correct this should be list will change this

2023-01-12 23:52 UTC, lhercot requested changes

2023-01-12 23:52 UTC, lhercot commented on aci/data_source_aci_l3extout.go
> +							Deprecated: "Use tn_rtctrl_profile_dn instead of tn_rtctrl_profile_name",
I don't think we need the deprecation in the datasource

2023-01-12 23:52 UTC, lhercot commented on website/docs/d/l3_outside.html.markdown
> +  name           = "foo_l3_outside"
Why adding spaces here?

2023-01-12 23:52 UTC, lhercot commented on website/docs/d/l3_outside.html.markdown
> +* `relation_l3ext_rs_dampening_pol` - (Optional) Relation to class rtctrlProfile. Cardinality - N_TO_M. Type - Block.
Relation to Route Control Profile for Dampening Policies (class rtctrlProfile).

2023-01-12 23:52 UTC, lhercot commented on website/docs/r/l3_outside.html.markdown
> +* `relation_l3ext_rs_dampening_pol` - (Optional) Relation to class rtctrlProfile. Can't configure multiple Dampening Policies for the same address-family. Cardinality - N_TO_M. Type - Block.
Relation to Route Control Profile for Dampening Policies (class rtctrlProfile).

2023-01-12 23:52 UTC, lhercot commented on website/docs/r/l3_outside.html.markdown
> +* `relation_l3ext_rs_l3_dom_att` - (Optional) Relation to class extnwDomP. Cardinality - N_TO_ONE. Type - String.
Relation to a L3 Domain (class extnwDomP)

2023-01-12 23:52 UTC, lhercot commented on website/docs/d/l3_outside.html.markdown
> +* `relation_l3ext_rs_l3_dom_att` - (Optional) Relation to class extnwDomP.
Relation to a L3 Domain (class extnwDomP)

2023-01-12 23:52 UTC, lhercot commented on website/docs/d/l3_outside.html.markdown
> +* `relation_l3ext_rs_interleak_pol` - (Optional) Relation to class rtctrlProfile.
Relation to Route Profile for Interleak (class rtctrlProfile)

2023-01-12 23:52 UTC, lhercot commented on website/docs/r/l3_outside.html.markdown
> +* `relation_l3ext_rs_interleak_pol` - (Optional) Relation to class rtctrlProfile. Interleak Policy object should belong to the parent tenant or be a shared object. Cardinality - N_TO_ONE. Type - Stri
Relation to Route Profile for Interleak (class rtctrlProfile)

2023-01-12 23:52 UTC, lhercot commented on website/docs/r/l3_outside.html.markdown
> +* `relation_l3ext_rs_ectx` - (Optional) Relation to class fvCtx. Target VRF object should belong to the parent tenant or be a shared object. Cardinality - N_TO_ONE. Type - String.
Relation to VRF (class fvCtx)

2023-01-12 23:52 UTC, lhercot commented on website/docs/d/l3_outside.html.markdown
> +* `relation_l3ext_rs_ectx` - (Optional) Relation to class fvCtx.
Relation to VRF (class fvCtx)

2023-01-12 23:52 UTC, lhercot commented on aci/data_source_aci_l3extout.go
> +			"relation_l3ext_rs_out_to_bd_public_subnet_holder": &schema.Schema{
This is not configurable so I think we should not add it.

2023-01-17 09:54 UTC, lhercot submitted a review, later dismissed
LGTM

2023-01-17 17:59 UTC, akinross commented on aci/resource_aci_l3extout.go
> +		Schema: AppendBaseAttrSchema(AppendNameAliasAttrSchema(map[string]*schema.Schema{
should we add mplsEnabled attribute as shown in model-doc?

2023-01-17 18:00 UTC, akinross commented on aci/resource_aci_l3extout.go
>  			"relation_l3ext_rs_dampening_pol": &schema.Schema{
should we check adding all other missing relationshipss?

2023-01-17 18:09 UTC, akinross commented on website/docs/d/l3_outside.html.markdown
> +* `relation_l3ext_rs_ectx` - (Optional) Relation to VRF (class fvCtx).
should we include cardinality and extra description for these as is done in the resource?

2023-01-18 15:15 UTC, lhercot approved these changes
LGTM

2023-01-18 15:19 UTC, akinross approved these changes
LGTM

2023-01-18 15:54 UTC, merged