Fixed resource_aci_l3extinstp idempotency and relationship attribute import issues
CiscoDevNet/terraform-provider-aci pull request #976
Opened 2022-12-13 12:16 UTC by sajagana

Note:

Fixed External EPGs resource issues, updated existing documents and example files.

2023-01-16 21:27 UTC, lhercot requested changes
Please also rebase on latest master

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_sec_inherited` - (Optional) Relation to class fvEPg. Cardinality - N_TO_M. Type - Set of String.
Relation to EPGs to be used as Contract Masters (class fvEPg).

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_prov` - (Optional) Relation to class vzBrCP. Cardinality - N_TO_M. Type - Set of String.
Relation to Provided Contracts (class vzBrCP).

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_cons` - (Optional) Relation to class vzBrCP. Cardinality - N_TO_M. Type - Set of String.
Relation to Consumed Contracts (class vzBrCP).

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_cons_if` - (Optional) Relation to class vzCPIf. Cardinality - N_TO_M. Type - Set of String.
Relation to Provided Contract Interfaces (class vzCPIf).

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_l3ext_rs_inst_p_to_profile` - (Optional) Relation to class rtctrlProfile. Cardinality - N_TO_M. Type: Block.
Relation to Route Control Profiles (class rtctrlProfile)

2023-01-16 21:27 UTC, lhercot commented on website/docs/d/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_prot_by` - (Optional) Relation to class vzTaboo. Cardinality - N_TO_M. Type - Set of String.
Relation to Taboo Contracts (vzTaboo).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_prot_by` - (Optional) Relation to class vzTaboo. Cardinality - N_TO_M. Type - Set of String.
Relation to Taboo Contracts (vzTaboo).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_cons` - (Optional) Relation to class vzBrCP. Cardinality - N_TO_M. Type - Set of String.
Relation to Consumed Contracts (class vzBrCP).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_l3ext_rs_inst_p_to_profile` - (Optional) Relation to class rtctrlProfile. Every direction(export/import) allows only one object. Cardinality - N_TO_M. Type: Block.
Relation to Route Control Profiles (class rtctrlProfile)

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_cons_if` - (Optional) Relation to class vzCPIf. Cardinality - N_TO_M. Type - Set of String.
Relation to Provided Contract Interfaces (class vzCPIf).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_prov` - (Optional) Relation to class vzBrCP. Cardinality - N_TO_M. Type - Set of String.
Relation to Provided Contracts (class vzBrCP).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `relation_fv_rs_sec_inherited` - (Optional) Relation to class fvEPg. Cardinality - N_TO_M. Type - Set of String.
Relation to EPGs to be used as Contract Masters (class fvEPg).

2023-01-16 21:27 UTC, lhercot commented on website/docs/r/external_network_instance_profile.html.markdown
> +* `pref_gr_memb` - (Optional) Represents parameter used to determine if EPg is part of a group that does not a contract for communication. Allowed values are "include" and "exclude". Default is "excl
if an External EPG is part of a group that does not require a contract for communication

2023-01-17 10:06 UTC, lhercot approved these changes
LGTM

2023-01-17 16:44 UTC, akinross approved these changes
LGTM

2023-01-17 18:56 UTC, merged